apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-product-config
  labels:
    app: postgres-product
data:
  POSTGRES_DB: product
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-product-pv-volume
  labels:
    type: local
    app: postgres-product
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres/postgres_product"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-product-pv-claim
  labels:
    app: postgres-product
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-product
  labels:
    app: postgres-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product
  template:
    metadata:
      labels:
        app: postgres-product
    spec:
      containers:
        - name: postgres-product
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-product-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-product-db
      volumes:
        - name: postgres-product-db
          persistentVolumeClaim:
            claimName: postgres-product-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-product
  labels:
    app: postgres-product
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres-product
