apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
    - image: soedomoto/stock-service
      jib: {}
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - target/classes/META-INF/dekorate/*.json
#      - k8s/*.yaml